[project]
name = "dagster_plus_plus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
  "dagster>=1.13.18",
  "dagster-docker>=0.29.18",
  "dagster-postgres>=0.29.18",
  "dagster-webserver>=1.13.18",
  "dbt>=1.0.0.40.18",
  "dbt-core>=1.11.13",
  "pdf2image>=1.17.0",
  "peewee>=4.3.0",
  "pendulum>=3.2.0",
  "pillow>=12.3.0",
  "psycopg>=3.3.4",
  "pypdf>=6.16.1",
  "pytesseract>=0.3.13",
  "returns>=0.29.0",
]

[project.scripts]
dagster-eigen = "dagster_plus_plus:main"

[dependency-groups]
dev = [
  "create-dagster>=1.13.18",
  "dagster-dg-cli>=1.13.18",
  "pre-commit>=4.6.2",
  "ruff>=0.16.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "dagster_plus_plus"
registry_modules = [
  "dagster_plus_plus.components.*",
]

[tool.hatch.build.targets.wheel]
force-include = { "pyproject.toml" = "pyproject.toml" }
