"""
Defines how to communicate with an external datastore, how to encode / decode
various objects, and how to load a data store component into the IO manager.
"""

import abc
import contextlib
from typing import Any

import attrs
import dagster as dag
from returns.io import IOResultE


@attrs.define
class ResourceRequiringDBConnection(abc.ABC):
    """
    Some resource whose sole responsibility is to create a DB
    connection.
    """

    @abc.abstractmethod
    def create_resource(self, _) -> Any:
        """Creates the resource as an object."""


@attrs.define
class IOKey:
    """
    An object representing the different components of the key. This is pertinent
    for the core I/O manager. Different data stores require different
    ways of storing data (think redis vs postgres). Having an object that stores
    this information will help individual data stores organize IO outputs.
    """

    upstream_name: str
    """
    The ``__`` separated asset key / op definition name that produced a value.
    """
    partition_key: str = attrs.field(converter=lambda x: x or "", default="")
    """
    If Dagster run was partitioned, ``context.partition_key`` will fill this in.
    Is relevant for assets and ops in a graph asset that are partitioned.
    """
    dynamic_output_mapping_key: str = attrs.field(
        converter=lambda x: x or "", default=""
    )
    """
    The mapping key that ties a dynamic output in an op to its value. Is not relevant
    for assets or ops that do not produce dynamic outputs.
    """
    op_output_name: str = attrs.field(converter=lambda x: x or "", default="")
    """
    If an op returns multiple values, this differentiates one return value from
    the other.
    """

    @classmethod
    def generate_key_from_event_log_record(cls, elr: dag.EventLogRecord):
        """Just uses the asset key and partition key if able."""
        if not elr.asset_key:
            raise ValueError("The event log record needs to contain an asset key.")
        return cls.generate_key_for_asset(elr.asset_key, elr.partition_key)

    @classmethod
    def generate_key_from_output_context(cls, context: dag.OutputContext):
        """To generate an IO key from the output context in an IOManager"""
        pk = context.partition_key if context.has_partition_key else ""
        if context.has_asset_key:
            context.log.debug(f"Writing output for {context.asset_key!r}")
            return cls.generate_key_for_asset(context.asset_key, pk)
        context.log.debug("Writing output for an op in a graph asset.")
        return cls.generate_key_for_op_in_graph_asset(context, context.op_def, pk)

    @classmethod
    def generate_key_for_asset(
        cls, asset_key: dag.AssetKey, partition_key: str | None = ""
    ):
        """
        Instantiate the object based off the unique asset key.
        """
        fully_qualified_name = "__".join(asset_key.path)
        return cls(fully_qualified_name, partition_key=partition_key)

    @classmethod
    def generate_key_for_op_in_graph_asset(
        cls,
        output_context: dag.OutputContext,
        op_def: dag.OpDefinition,
        partition_key: str = "",
    ):
        """Format the key based off an op in some graph asset pipeline"""
        self = cls(op_def.name, partition_key=partition_key)
        if output_context.mapping_key:
            self.dynamic_output_mapping_key = output_context.mapping_key
        with contextlib.suppress(dag.DagsterInvariantViolationError):
            self.op_output_name = output_context.name
        return self


@attrs.define
class BaseIODataStore(abc.ABC):
    """
    Say you have to store data into a giant monolith of a postgres table, or a series
    of key/value pairs in redis. Create your own datastore object that will allow the
    I/O manager automatically / arbitrarily fetch the data you need for your op /
    asset.
    """

    @abc.abstractmethod
    def read(self, key: IOKey) -> IOResultE[str]:
        """Either you get the b64 string, or you don't and return a failure."""

    @abc.abstractmethod
    def read_metadata(self, key: IOKey) -> IOResultE[dict[str, Any]]:
        """Get the metadata generated by ``context.add_output_metadata``"""

    @abc.abstractmethod
    def write(
        self, key: IOKey, value: str, metadata: dict[str, Any] | None = None
    ) -> None:
        """Write a string encoded value to the datastore."""


@attrs.define
class BaseDataStore(abc.ABC):
    """
    Treat this data store as something you can freely add / subtract to however
    many times you want.

    Add simple things here that don't require too much overhead. Examples are
    authentication tokens, values that you'd need to pass to other assets mid-job,
    locks to access shared memory across jobs, document objects to represent
    individual files in pipeline, etc.
    """

    @abc.abstractmethod
    def read(self, key: str) -> IOResultE[Any]:
        """You should not need some overly complicated key."""

    @abc.abstractmethod
    def write(self, key: str, *args, **kwargs) -> None:
        """Simply set the value to anything"""


@attrs.define
class BaseCache(BaseDataStore, abc.ABC):
    """
    A class that inherits from this will be operating as a cache, which typically
    means when the process dies, the table data will be lost.
    """

    @abc.abstractmethod
    def pop(self, key: str) -> IOResultE[Any]:
        """Reads the key (if it exists), deletes it, then returns the value."""

    @abc.abstractmethod
    def write(self, key: str, value: Any) -> None:
        """Caches are simple. Writing should be too."""
