---
name: dev-sip

services:
    # The postgres DB used by Dagster for run storage, schedule storage, and event log storage.
    postgres:
        image: nexus.eigen.live/bitnami/postgresql:15.5.0-debian-11-r18
        container_name: postgres-sip-dev
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DAGSTER_POSTGRES_USER:?.env not set up correctly}
            POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD:?.env not set up correctly}
            POSTGRES_DB: ${DAGSTER_POSTGRES_NAME:?.env not set up correctly}
            POSTGRES_INITDB_ARGS: --encoding='UTF-8'
        ports:
          - 5432:5432
        networks:
          - sip-network

networks:
    sip-network:
        driver: bridge
        name: sip-network
