---
services:
    postgres:
        image: nexus.eigen.live/bitnami/postgresql:15.5.0-debian-11-r18
        container_name: postgres-sip
        restart: unless-stopped
        environment:
            POSTGRESQL_USERNAME: $DAGSTER_POSTGRES_USER
            POSTGRESQL_PASSWORD: $DAGSTER_POSTGRES_PASSWORD
            POSTGRESQL_DATABASE: $DAGSTER_POSTGRES_NAME
            POSTGRESQL_INITDB_ARGS: --encoding='UTF-8'
        volumes:
          - postgres:/bitnami/postgresql
        networks:
          - sip-network
        healthcheck:
            test: pg_isready -U dagster || exit 1
            interval: 30s
            timeout: 20s
            retries: 5
            start_period: 15s
        security_opt:
          - no-new-privileges
    grpc:
        image: ${SIP_IMAGE}:$SIP_VERSION
        container_name: grpc-sip
        depends_on:
          - postgres
        restart: unless-stopped
        env_file:
          - .env
        entrypoint: /entrypoints/grpc.sh
        networks:
          - sip-network
        healthcheck:
            test: dagster api grpc-health-check -p 4000 || exit 1
            interval: 30s
            timeout: 20s
            retries: 5
            start_period: 15s
    web:
        image: ${SIP_IMAGE}:${SIP_VERSION}
        container_name: web-sip
        restart: unless-stopped
        env_file:
          - .env
        entrypoint: /entrypoints/web.sh
        volumes:
          - /tmp/sip/io_manager_storage:/tmp/io_manager_storage
        ports:
          - 3001:3001
        networks:
          - sip-network
          - eigen-network
        depends_on:
          - postgres
          - grpc
        healthcheck:
            test: curl -I --fail http://localhost:3001/server_info || exit 1
            interval: 30s
            timeout: 20s
            retries: 5
            start_period: 15s
    daemon:
        image: ${SIP_IMAGE}:${SIP_VERSION}
        container_name: daemon-sip
        restart: unless-stopped
        env_file:
          - .env
        entrypoint: /entrypoints/daemon.sh
        volumes:
          - ./dagster.yaml:/opt/dagster/sip/dagster.yaml
          - ./filesystem_mount:/opt/filesystem_mount
          - /tmp/sip/io_manager_storage:/tmp/io_manager_storage
        networks:
          - sip-network
          - eigen-network
        depends_on:
          - postgres
          - grpc
        healthcheck:
            test: dagster-daemon liveness-check || exit 1
            interval: 30s
            timeout: 20s
            retries: 5
            start_period: 15s

networks:
    sip-network:
        driver: bridge
        name: sip-network
    eigen-network:
        external:
            name: eigen_all_services

volumes:
    postgres:
    redis:
